nation3/citizen-directory

- package.json
- pages/index.tsx
- yarn.lock
https://app.dework.xyz/nation3/nationcred-p?taskId=06273af6-2304-45f9-9fb7-c33c4ab73b58
closes #6
> <img width="821" alt="Screen Shot 2022-11-05 at 4 32 18 PM" src="https://user-images.githubusercontent.com/95955389/200111419-3940a762-b58f-4bc5-ba9b-625ebc93b701.png">
> feat: fetch chart data from datasets repo

- package.json
- pages/index.tsx
- yarn.lock
Fix build errors to enable `yarn start`
> Prepare for Vercel deployment

- components/CitizenCard.tsx
- pages/index.tsx
https://app.dework.xyz/nation3/nationcred-p?taskId=44ff5cb1-92da-43be-9804-6498ca5c0088
> <img width="810" alt="Screenshot 2022-11-15 at 3 45 38 PM" src="https://user-images.githubusercontent.com/95955389/201873126-5b16c8ec-9138-4298-b05f-432713aa6689.png">
> feat: display voting power per citizen

- pages/[passportId].tsx
https://app.dework.xyz/nation3/nationcred-p?taskId=2b628c92-c2d9-4421-b30f-be4572edd168
> <img width="833" alt="Screenshot 2022-12-09 at 6 26 36 PM" src="https://user-images.githubusercontent.com/95955389/206681560-c4db3042-a8f9-4b55-8766-5e5103ffe0c2.png">
> feat: visualize historical voting power per citizen

- pages/index.tsx
> feat: display active citizens in chart

- pages/[passportId].tsx
> Tonyalpha/dw 974/citizen directory sepa

- pages/[passportId].tsx
> <img width="820" alt="Screenshot 2023-01-05 at 7 32 52 PM" src="https://user-images.githubusercontent.com/95955389/210771354-84bde8ec-a428-4edf-93a3-66558dddace0.png">
> <img width="810" alt="Screenshot 2023-01-05 at 7 34 52 PM" src="https://user-images.githubusercontent.com/95955389/210771383-1bc3aec4-5654-47cb-a37f-5f73457ea73f.png">
> Only use positive y-scale

- src/pages/[passportId].tsx
#14
Example: https://citizen-directory-git-visualize-ven-969a72-nation3-dao-transfer.vercel.app/172
> ![](https://github.com/nation3/citizen-directory/assets/95955389/9b82bcdd-6966-435c-9d61-2a3e34a956ef)
> feat: visualize veNATION (#14)

- src/pages/[passportId].tsx
#14
https://citizen-directory-git-feat-add-dewo-53e1c5-nation3-dao-transfer.vercel.app/172
> ![](https://github.com/nation3/citizen-directory/assets/95955389/98b471ef-befd-4913-bf7a-bf13b139c401)
> feat: add dework chart (#14)

- src/pages/[passportId].tsx
#14
> ![](https://github.com/nation3/citizen-directory/assets/95955389/113be036-fa80-4bf8-bc82-530582a1328b)
Example:  https://citizen-directory-git-feat-add-disc-0b337e-nation3-dao-transfer.vercel.app/172
> feat: add discourse chart (#14)

- abis/VotingEscrow.json
- hooks/useIsMounted.tsx
- package-lock.json
- package.json
- src/components/VeNationLockDetails.tsx
- src/pages/[passportId].tsx
- src/pages/_app.tsx
> ![](https://github.com/nation3/citizen-directory/assets/95955389/bcec88c7-dac6-4edb-b149-a13977736b55)
Examples:
- https://citizen-directory-git-display-venat-bc6f0a-nation3-dao-transfer.vercel.app/172
- https://citizen-directory-git-display-venat-bc6f0a-nation3-dao-transfer.vercel.app/280
> Display $veNATION lock details

- src/pages/[passportId].tsx
Before:
> ![](https://github.com/nation3/citizen-directory/assets/95955389/18039c4a-9e19-4a09-9fef-63f561f3f3ff)
After:
> ![](https://github.com/nation3/citizen-directory/assets/95955389/f5a64425-93ff-4f7c-8994-2ab2e59b36df)
> Rename voting power

- README.md
add a link to the deployment env local host
> add a link to the deployment env local host

- src/components/Menu.tsx
- src/pages/[passportId].tsx
> Display cumulative NationCred score (#50)

- src/pages/[passportId].tsx
close #55
Sample:  https://citizen-directory-8y7viwtw2-nation3-dao-transfer.vercel.app/171
> ![](https://github.com/nation3/citizen-directory/assets/95955389/223f2d32-e3b7-47e9-bdeb-fe00dc3049ad)
> ![after](https://github.com/nation3/citizen-directory/assets/95955389/0e434817-6fd6-48cb-97ec-a8d010adc4c3)
> feat: activity status indicator to chart (#55)

- src/pages/index.tsx
close #35
> ![](https://github.com/nation3/citizen-directory/assets/95955389/eaeccac6-1af3-40b6-aab9-9745f3c485cb)
> NationCred scores in list of profiles (#35)

- src/pages/index.tsx
close #51
> ![](https://github.com/nation3/citizen-directory/assets/95955389/f4506f13-f0ec-4852-a5bd-be4cd096f9b0)
> Display revocation count (#51)

- abis/DeveloperSkillLevels.json
- src/components/NFTImage.tsx
- src/components/ProfileDetailsDevSkillRating.tsx
- src/pages/[passportId].tsx
close #64
> ![](https://github.com/nation3/citizen-directory/assets/95955389/858fa92b-4827-400d-8661-77d9f66b1b37)
> 🧙 feat: dev skill level (#64)

- abis/OperatorSkillLevels.json
- src/components/ProfileDetailsOpsSkillRating.tsx
- src/pages/[passportId].tsx
> ⚙️ feat: ops skill level (#65)

- src/styles/globals.css
Fixes the axis label colors on dark mode
Dark Mode
Light Mode
> fix: 🐞 axis label color on dark mode
